#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Oct 22 13:41:32 2018

@author: Kavitha
"""

'''
Exercise: eval quadratic
5.0/5.0 points (graded)
ESTIMATED TIME TO COMPLETE: 5 minutes

Write a Python function, evalQuadratic(a, b, c, x), that returns the value of the quadratic 
a
⋅
x
2
+
b
⋅
x
+
c
.

This function takes in four numbers and returns a single number.
'''


def evalQuadratic(a, b, c, x):
    '''
    a, b, c: numerical values for the coefficients of a quadratic equation
    x: numerical value at which to evaluate the quadratic.
    '''
    y=(a*(x**2))+(x*b)+c
    return y



##Correct