#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Oct 22 13:40:16 2018

@author: Kavitha
"""

'''
Exercise: square
5.0/5.0 points (graded)
ESTIMATED TIME TO COMPLETE: 3 minutes

Write a Python function, square, that takes in one number and returns the square of that number.

This function takes in one number and returns one number.
'''


def square(x):
    '''
    x: int or float.
    '''
    sq=x**2
    return sq



##Correct