#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Oct  1 12:29:26 2018

@author: Kavitha
"""
##Problem 6
##20.0/20.0 points (graded)
##Write a function to flatten a list. The list contains other lists, strings, or ints. For example, [[1,'a',['cat'],2],[[[3]],'dog'],4,5] is flattened into [1,'a','cat',2,3,'dog',4,5] (order matters).

def flatten(aList):
    ''' 
    aList: a list 
    Returns a copy of aList, which is a flattened version of aList 
    '''
    new_list=[]
    for element in aList:
        if type(element)!=type([]):
            new_list.append(element)
        else:
            new_list.extend(flatten(element))
    aList[:]=new_list
    return aList


##Correct
            
            