#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Oct  1 12:12:17 2018

@author: Kavitha
"""
'''
Problem 3
10.0/10.0 points (graded)
Implement a function called closest_power that meets the specifications below.

For example,

closest_power(3,12) returns 2
closest_power(4,12) returns 2
closest_power(4,1) returns 0
'''



def closest_power(base, num):
    '''
    base: base of the exponential, integer > 1
    num: number you want to be closest to, integer > 0
    Find the integer exponent such that base**exponent is closest to num.
    Note that the base**exponent may be either greater or smaller than num.
    In case of a tie, return the smaller value.
    Returns the exponent.
    '''
    if base==num:
        return 1
    if base>num:
        return 0
    for exp in range(1,int(num)):
        if abs(base**exp-num)<= abs (base**(exp+1)-num):
            return exp



##Correct
    
        