#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Oct 22 12:39:45 2018

@author: Kavitha
"""

'''
Problem 7 - You and your Computer
20.0/20.0 points (graded)
Now that your computer can choose a word, you need to give the computer the option to play. Write the code that re-implements the playGame function. You will modify the function to behave as described below in the function's comments. As before, you should use the HAND_SIZE constant to determine the number of cards in a hand. Be sure to try out different values for HAND_SIZE with your program.
'''


def playGame(wordList):
    """
    Allow the user to play an arbitrary number of hands.
 
    1) Asks the user to input 'n' or 'r' or 'e'.
        * If the user inputs 'e', immediately exit the game.
        * If the user inputs anything that's not 'n', 'r', or 'e', keep asking them again.

    2) Asks the user to input a 'u' or a 'c'.
        * If the user inputs anything that's not 'c' or 'u', keep asking them again.

    3) Switch functionality based on the above choices:
        * If the user inputted 'n', play a new (random) hand.
        * Else, if the user inputted 'r', play the last hand again.
          But if no hand was played, output "You have not played a hand yet. 
          Please play a new hand first!"
        
        * If the user inputted 'u', let the user play the game
          with the selected hand, using playHand.
        * If the user inputted 'c', let the computer play the 
          game with the selected hand, using compPlayHand.

    4) After the computer or user has played the hand, repeat from step 1

    wordList: list (string)
    """
    dummy=''
    count=0
    while dummy=='':
        mainInput=str(input("Enter n to deal a new hand, r to replay the last hand, or e to end game:"))
        if mainInput=='e':
                break
        if (mainInput=='r') or (mainInput=='n'):
            while True:
                if mainInput=='r':
                    if count==0:
                        print("You have not played a hand yet. Please play a new hand first!")
                        break
                choice=str(input("Enter u to have yourself play, c to have the computer play: "))
                if mainInput=='n':
                    if choice=='u':
                        n= HAND_SIZE                       ##HAND_SIZE is a constant defined by the grader for this game. We can use our own n value to play here.
                        hand=dealHand(n)
                        playHand(hand, wordList, n)
                        count+=1
                        break
                    elif choice=='c':
                        n=HAND_SIZE                        ##HAND_SIZE is a constant defined by the grader for this game. We can use our own n value to play here.
                        hand=dealHand(n)
                        compPlayHand(hand, wordList, n)
                        count+=1
                        break
                    else:
                        print("Invalid command.")
                if mainInput=='r':
                    if choice=='u':
                        n=HAND_SIZE 
                        playHand(hand, wordList, n)
                        count+=1
                        break
                    elif choice=='c':
                        n=HAND_SIZE 
                        compPlayHand(hand, wordList, n)
                        count+=1
                        break
                    else:
                        print("Invalid command.")
                        print()
        else:
            print("Invalid command.")
            
            
            
            
##Correct