#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Oct 22 13:57:05 2018

@author: Kavitha
"""

'''
Grader
10.0/10.0 points (ungraded)
A regular polygon has n number of sides. Each side has length s.

The area of a regular polygon is: 
The perimeter of a polygon is: length of the boundary of the polygon
Write a function called polysum that takes 2 arguments, n and s. This function should sum the area and square of the perimeter of the regular polygon. The function returns the sum, rounded to 4 decimal places.
'''


from math import *
def polysum(n,s):
    area=(0.25*n*(s**2))/(tan(pi/n))
    perimeter=n*s
    sum=area+(perimeter**2)
    return round(sum,4)



##Correct