#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Oct 22 14:20:06 2018

@author: Kavitha
"""

'''
Exercise: apply to each 3
5.0/5.0 points (graded)
ESTIMATED TIME TO COMPLETE: 4 minutes

  >>> print testList
  [1, 16, 64, 81]
  '''
  
  
def mul(a):
    return a*a
applyToEach(testList, mul)



##Correct