#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Oct 22 14:19:04 2018

@author: Kavitha
"""

'''
Exercise: apply to each 2
5.0/5.0 points (graded)
ESTIMATED TIME TO COMPLETE: 4 minutes

  >>> print(testList)
  [2, -3, 9, -8]
  '''
  
  
def add(a):
    return a+1
applyToEach(testList, add)



##Correct