#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Oct 22 13:11:44 2018

@author: Kavitha
"""

'''
Exercise: while exercise 2
5.0/5.0 points (graded)
ESTIMATED TIME TO COMPLETE: 5 minutes

2. Convert the following into code that uses a while loop.

prints Hello!
prints 10
prints 8
prints 6
prints 4
prints 2
'''


print ("Hello!")
i=10
while i >=2:
    print (i)
    i-=2
    
    
##Correct