#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Oct 22 13:19:52 2018

@author: Kavitha
"""

'''
Exercise: for exercise 2
5.0/5.0 points (graded)

ESTIMATED TIME TO COMPLETE: 5 minutes

2. Convert the following code into code that uses a for loop.

prints "Hello!"
prints 10
prints 8
prints 6
prints 4
prints 2
'''


print("Hello!")
for x in range(10,0,-2):
    print(x)
    


##Correct

