#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Oct 22 13:02:17 2018

@author: Kavitha
"""

'''
Exercise: hello world
5.0/5.0 points (graded)
ESTIMATED TIME TO COMPLETE: 2 minutes

Write a piece of Python code that prints out the string hello world
'''


x="hello world"
print (x)


##correct